# Generated by Django 3.2.4 on 2022-04-29 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_productos_videoid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosDestacados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField(default=0, null=True)),
                ('oferta', models.BooleanField(default=False)),
                ('videoid', models.CharField(max_length=100, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categorias')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marcas')),
            ],
            options={
                'verbose_name': 'Productodestacado',
                'verbose_name_plural': 'Productosdestacados',
                'db_table': 'productosdestacados',
                'ordering': ['id'],
            },
        ),
    ]
