# Generated by Django 3.2.4 on 2022-04-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_productosdestacados'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='destacado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
