# Generated by Django 4.0.3 on 2022-05-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_comuna_metodo_pago_region_venta_provincia_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.comuna'),
        ),
    ]
