# Generated by Django 4.0.3 on 2022-05-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_venta_cliente_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['monto'], 'verbose_name': 'Monto', 'verbose_name_plural': 'Montos'},
        ),
    ]
