# Generated by Django 4.0.3 on 2022-05-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_venta_cliente_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField()),
                ('testt', models.CharField(max_length=50)),
                ('testtt', models.DateField()),
                ('testttt', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'db_table': 'test',
                'ordering': ['test'],
            },
        ),
    ]
