# Generated by Django 4.0.3 on 2022-05-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
