# Generated by Django 4.0.3 on 2022-05-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_delete_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venta',
            new_name='Ventas',
        ),
    ]
