# Generated by Django 4.0.3 on 2022-05-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_venta_ventas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio',
            options={'ordering': ['comuna_envio'], 'verbose_name': 'Comuna', 'verbose_name_plural': 'Comunas'},
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='comuna',
            new_name='comuna_envio',
        ),
        migrations.AlterModelTable(
            name='envio',
            table='comuna_envio',
        ),
    ]
