# Generated by Django 4.0.3 on 2022-05-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_envio_options_rename_comuna_envio_comuna_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='test',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
