# Generated by Django 4.0.3 on 2022-05-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_ventas_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventas',
            options={'ordering': ['montosadasd'], 'verbose_name': 'Monto', 'verbose_name_plural': 'Montos'},
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='monto',
            new_name='montosadasd',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='test',
        ),
        migrations.AlterModelTable(
            name='ventas',
            table='montosadasd',
        ),
    ]
