# Generated by Django 4.0.3 on 2022-05-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_ventas_options_rename_montosadasd_ventas_monto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ventas',
            new_name='Venta',
        ),
        migrations.AlterModelTable(
            name='comuna',
            table='Comuna',
        ),
        migrations.AlterModelTable(
            name='envio',
            table='Envio',
        ),
        migrations.AlterModelTable(
            name='metodo_pago',
            table='Metodo_Pago',
        ),
        migrations.AlterModelTable(
            name='provincia',
            table='Provincia',
        ),
        migrations.AlterModelTable(
            name='region',
            table='Region',
        ),
    ]
