# Generated by Django 4.0.3 on 2022-05-20 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0034_rename_ventas_venta_alter_comuna_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
