# Generated by Django 4.0.3 on 2022-05-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_categoria_marca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
