# Generated by Django 4.0.3 on 2022-05-20 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_delete_categoria_delete_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=150)),
                ('sector_comercial', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('num_documento', models.IntegerField(max_length=11)),
                ('telefono', models.IntegerField(max_length=9)),
                ('email', models.EmailField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.comuna')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
                'ordering': ['nombre'],
            },
        ),
    ]
