# Generated by Django 3.2.4 on 2022-05-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='num_documento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
