# Generated by Django 3.2.4 on 2022-05-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20220520_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('stock_inicial', models.IntegerField()),
                ('stock_actual', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalle_Ingreso',
                'verbose_name_plural': 'Detalle_Ingresos',
                'db_table': 'Detalle_Ingreso',
                'ordering': ['precio_compra'],
            },
        ),
    ]
