# Generated by Django 3.2.4 on 2022-05-21 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_detalle_ingreso_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='ingreso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.detalle_ingreso'),
            preserve_default=False,
        ),
    ]
