# Generated by Django 3.2.4 on 2022-05-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_productos_ingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='ingreso',
            new_name='detalle_ingreso',
        ),
    ]
