# Generated by Django 3.2.4 on 2022-05-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_rename_ingreso_productos_detalle_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito_Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('cod_producto', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Carrito_Compras',
                'verbose_name_plural': 'Carrito_Compras',
                'db_table': 'Carrito_Compras',
                'ordering': ['id'],
            },
        ),
    ]
